### ISSUE TITLE
How do I github

### ISSUE THREAD

**Issue by malpaslan** [jradavenport/Gender-in-Astro#13]
Okay, so I think I've managed to go so far as to figuring out how to post on github that I have no idea how to use github. I mainly just want to figure out how to upload PDFs of plots to this thing.

Anyway, if I'm needed to get anything done, it might be a good idea to contact me on mehmet.alpaslan@nasa.gov instead of on here.

**Comment by jradavenport** [comment]
If you can post and join the discussion (which you clearly can!) then you'll be able to definitely help!

Nominally you would contribute code/data/figures to the project using [Pull Requests](https://guides.github.com/activities/hello-world/#pr), though I feel this machinery is a bit obtuse. 

For the paper, my plan was to use ShareLatex or Authorea
