### ISSUE TITLE
Server for web form

### ISSUE THREAD

**Issue by willettk** [jradavenport/Gender-in-Astro#2]
Do we need a permanent server for the PHP webform to work? @jradavenport - how is it set up for the AAS data?

**Comment by jradavenport** [comment]
For my AAS studies I put it on my UW webspace, which has PHP running.

I think a server for this would be a great idea. One possibility is hooking it in to Google Docs. Another could be a small AWS instance or something similar and cheap? Or if you have local webspace that would work good too!

**Comment by willettk** [comment]
I have some local webspace at UMN, but that's also potentially going away
in 1 yr with wherever I end up.

Google might be good (I don't know how much interest we'll get if it's
worth spinning up an AWS instance). Do you have any experience with the
Google Drive API, @jradavenport?

**Comment by jradavenport** [comment]
I have zero Google Drive API experience, unfortunately...

**Comment by jradavenport** [comment]
My current host institution has provided us with a good home for now!
http://aasgender.wwu.edu
